// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkcvlvzwhzzdrvmevvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrY3Zsdnp3aHp6ZHJ2bWV2dm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2MDU4NTAsImV4cCI6MjEwNTE4MTg1MH0.z3ptd7z1y_geu8Fn3AH3YOkZJWu-aHcLnB_LgJAOuxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});